{% set name = "flytekit" %}
{% set version = "1.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flytekit-{{ version }}.tar.gz
  sha256: c2eeec3fd52b8ebfc0ee63e7da584c2f9d0a15d0d37aa085a2385fd1a2d3f18f

build:
  entry_points:
    - pyflyte-execute=flytekit.bin.entrypoint:execute_task_cmd
    - pyflyte-fast-execute=flytekit.bin.entrypoint:fast_execute_task_cmd
    - pyflyte-map-execute=flytekit.bin.entrypoint:map_execute_task_cmd
    - pyflyte=flytekit.clis.sdk_in_container.pyflyte:main
    - flyte-cli=flytekit.clis.flyte_cli.main:_flyte_cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8, <3.13
  run:
    - jinja2
    - jsonlines
    - adlfs >=2023.3.0
    - click >=6.6,<9.0
    - cloudpickle >=2.0.0
    - croniter >=0.3.20,<4.0.0
    - dataclasses-json >=0.5.2,<0.5.12
    - diskcache >=5.2.1
    - docker-py >=4.0.0,<7.0.0
    - docstring_parser >=0.9.0
    - flyteidl >=1.11.0b1
    - fsspec >=2023.3.0
    - gcsfs >=2023.3.0
    - googleapis-common-protos >=1.57
    - grpcio
    - grpcio-status
    - importlib-metadata
    - isodate
    - joblib
    - jsonpickle
    - keyring >=18.0.1
    - markdown-it-py
    - marshmallow-enum
    - marshmallow-jsonschema >=0.12.0
    - mashumaro >=3.11
    - protobuf !=4.25.0
    - pyarrow
    - pygments
    - python >=3.8,<3.12
    - python-json-logger >=2.0.0
    - pytimeparse >=1.1.8,<2.0.0
    - pyyaml !=6.0.0,!=5.4.0,!=5.4.1
    - requests >=2.18.4,<3.0.0,!=2.32.0,!=2.32.1,!=2.32.2,!=2.32.3
    - rich
    - rich-click
    - s3fs >=2023.3.0,!=2024.3.1
    - statsd >=3.0.0,<4.0.0
    - typing-extensions
    - urllib3 >=1.22,<3.0.0

test:
  files:
    - example.py
  imports:
    - flytekit
  commands:
    - pip check
    - pyflyte-execute --help
    - pyflyte-fast-execute --help
    - pyflyte-map-execute --help
    - pyflyte --help
    - flyte-cli --help
    - pyflyte run example.py hello_world_wf --name foobar
  requires:
    - pip

about:
  home: https://github.com/flyteorg/flytekit
  summary: Flyte SDK for Python
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    Flytekit Python is the Python Library for easily authoring, testing, deploying, 
    and interacting with Flyte tasks, workflows, and launch plans.

    - Flyte HomePage: https://flyte.org
    - Flyte Docs: http://docs.flyte.org/

    PyPI: [https://pypi.org/project/flytekit/](https://pypi.org/project/flytekit/)

  doc_url: https://flytecookbook.readthedocs.io/en/latest/
  dev_url: https://github.com/flyteorg/flytekit

extra:
  recipe-maintainers:
    - bstadlbauer
    - eapolinario
    - cosmicBboy
    - bmcconeghy
    - asford
    - sugatoray
