{% set name = "flytekit" %}
{% set version = "1.14.5" %}
{% set python_min = python_min|default("3.9") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flytekit-{{ version }}.tar.gz
  sha256: d1c920354e7b919999a19e6de5b689980cedc5cea4405902f95a079f04577018

build:
  entry_points:
    - pyflyte-execute=flytekit.bin.entrypoint:execute_task_cmd
    - pyflyte-fast-execute=flytekit.bin.entrypoint:fast_execute_task_cmd
    - pyflyte-map-execute=flytekit.bin.entrypoint:map_execute_task_cmd
    - pyflyte=flytekit.clis.sdk_in_container.pyflyte:main
    - flyte-cli=flytekit.clis.flyte_cli.main:_flyte_cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8, <3.13
    - setuptools
  run:
    - msgpack-python >=1.1.0
    - typing_extensions
    - numpy <2
    - jinja2
    - jsonlines
    - adlfs >=2023.3.0
    - click >=6.6
    - cloudpickle >=2.0.0
    - croniter >=0.3.20
    - dataclasses-json >=0.5.2,<0.5.12
    - diskcache >=5.2.1
    - docker-py >=4.0.0
    - docstring_parser >=0.9.0
    - flyteidl >=1.13.9
    - fsspec >=2023.3.0
    - gcsfs >=2023.3.0
    - googleapis-common-protos >=1.57
    - grpcio !=1.68.0,!=1.68.1
    - grpcio-status !=1.68.0,!=1.68.1
    - importlib-metadata
    - isodate
    - joblib
    - jsonpickle
    - keyring >=18.0.1
    - markdown-it-py
    - marshmallow-enum
    - marshmallow-jsonschema >=0.12.0
    - mashumaro >=3.15
    - protobuf !=4.25.0
    - pyarrow
    - pygments
    - python >={{ python_min }},<3.12
    - python-json-logger >=2.0.0
    - pytimeparse >=1.1.8
    - pyyaml !=6.0.0,!=5.4.0,!=5.4.1
    - requests >=2.18.4
    - rich
    - rich-click
    - s3fs >=2023.3.0,!=2024.3.1
    - statsd >=3.0.0
    - typing-extensions
    - urllib3 >=1.22

test:
  files:
    - example.py
    - example-inputs.json
  imports:
    - flytekit
  commands:
    - pip check
    - pyflyte-execute --help
    - pyflyte-fast-execute --help
    - pyflyte-map-execute --help
    - pyflyte --help
    - flyte-cli --help
    - pyflyte run example.py hello_world_wf --inputs-file example-inputs.json
  requires:
    - pip <24.2
    - python ={{ python_min }}

about:
  home: https://github.com/flyteorg/flytekit
  summary: Flyte SDK for Python
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    Flytekit Python is the Python Library for easily authoring, testing, deploying, 
    and interacting with Flyte tasks, workflows, and launch plans.

    - Flyte HomePage: https://flyte.org
    - Flyte Docs: http://docs.flyte.org/

    PyPI: [https://pypi.org/project/flytekit/](https://pypi.org/project/flytekit/)

  doc_url: https://flytecookbook.readthedocs.io/en/latest/
  dev_url: https://github.com/flyteorg/flytekit

extra:
  recipe-maintainers:
    - bstadlbauer
    - eapolinario
    - cosmicBboy
    - bmcconeghy
    - asford
    - sugatoray
