{% set name = "flytekit" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Directly install .whl build, due to upstream .tar.gz dist error
  # Here including both:
  # * .tar.gz, for LICENSE
  # * .whl, for code
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flytekit-{{ version }}.tar.gz
    sha256: 45721c2eae47edd06c61be160a12d5058117ed6b1201d62d1b81582fb00aed24
    folder: .
  - url: https://files.pythonhosted.org/packages/7c/a9/307368ce4d9040378e738cb46990528827ce8de46a19a65a3a2cb5e89337/flytekit-1.1.0-py3-none-any.whl
    sha256: 4686a0e02e71e7ab1aff4a79ba8976be7ef63767e8c853a3824a88e182f9df4e
    fn: flytekit-{{ version }}-py3-none-any.whl
    folder: .

build:
  number: 0
  noarch: python
  entry_points:
    - pyflyte-execute=flytekit.bin.entrypoint:execute_task_cmd
    - pyflyte-fast-execute=flytekit.bin.entrypoint:fast_execute_task_cmd
    - pyflyte-map-execute=flytekit.bin.entrypoint:map_execute_task_cmd
    - pyflyte=flytekit.clis.sdk_in_container.pyflyte:main
    - flyte-cli=flytekit.clis.flyte_cli.main:_flyte_cli
  # Install from wheel, revert to standard pip install -vv . after:
  # https://github.com/flyteorg/flytekit/pull/1088
  script: {{ PYTHON }} -m pip install -vv flytekit-{{ version }}-py3-none-any.whl

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - click >=6.6,<9.0
    - cloudpickle >=2.0.0
    - cookiecutter >=1.7.3
    - croniter >=0.3.20,<4.0.0
    - dataclasses-json >=0.5.2
    - deprecated >=1.0,<2.0
    - diskcache >=5.2.1
    - docker-py >=5.0.3,<6.0.0
    - docker-image-py >=0.1.10
    - docstring_parser >=0.9.0
    - flyteidl >=1.1.3,<1.2.0
    - grpcio >=1.43.0,<2.0 # upstream blocks grpcio 1.45.0, but build is present in conda-forge
    - grpcio-status >=1.43 # upstream blocks grpcio 1.45.0, but build is present in conda-forge
    - importlib-metadata
    - keyring >=18.0.1
    - marshmallow-jsonschema >=0.12.0
    - natsort >=7.0.1
    - numpy
    - pandas >=1.0.0,<2.0.0
    - protobuf >=3.6.1,<4
    - pyarrow >=4.0.0,<7.0.0
    - pyopenssl
    - python-dateutil >=2.1
    - python-json-logger >=2.0.0
    - pytimeparse >=1.1.8,<2.0.0
    - pytz
    - pyyaml
    - requests >=2.18.4,<3.0.0
    - responses >=0.10.7
    - retry ==0.9.2
    - sortedcontainers >=1.5.9,<3.0.0
    - statsd >=3.0.0,<4.0.0
    - typing-extensions
    - urllib3 >=1.22,<2.0.0
    - wheel >=0.30.0,<1.0.0
    - wrapt >=1.0.0,<2.0.0

test:
  files:
    - example.py
  imports:
    - flytekit
    - flytekit.bin
  commands:
    - pip check
    - pyflyte-execute --help
    - pyflyte-fast-execute --help
    - pyflyte-map-execute --help
    - pyflyte --help
    - flyte-cli --help
    - pyflyte run example.py wf --n 500 --mean 42 --sigma 2
  requires:
    - pip

about:
  home: https://github.com/flyteorg/flytekit
  summary: Flyte SDK for Python
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    Flytekit Python is the Python Library for easily authoring, testing, deploying, 
    and interacting with Flyte tasks, workflows, and launch plans.

    - Flyte HomePage: https://flyte.org
    - Flyte Docs: http://docs.flyte.org/

    PyPI: [https://pypi.org/project/flytekit/](https://pypi.org/project/flytekit/)

  doc_url: https://flytecookbook.readthedocs.io/en/latest/
  dev_url: https://github.com/flyteorg/flytekit

extra:
  recipe-maintainers:
    - bmcconeghy
    - asford
    - sugatoray
