{% set name = "flytekit" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flytekit-{{ version }}.tar.gz
  sha256: 07bb88f5ec1b663bbf3a0e9e073e14880cbb775c58e281cfba654553b77fd5ef

build:
  entry_points:
    - pyflyte-execute=flytekit.bin.entrypoint:execute_task_cmd
    - pyflyte-fast-execute=flytekit.bin.entrypoint:fast_execute_task_cmd
    - pyflyte-map-execute=flytekit.bin.entrypoint:map_execute_task_cmd
    - pyflyte=flytekit.clis.sdk_in_container.pyflyte:main
    - flyte-cli=flytekit.clis.flyte_cli.main:_flyte_cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8, <3.12
  run:
    - adlfs
    - gitpython
    - googleapis-common-protos >=1.57
    - typing-extensions
    - python >=3.8,<3.12
    - click >=6.6,<9.0
    - cloudpickle >=2.0.0
    - cookiecutter >=1.7.3
    - croniter >=0.3.20,<4.0.0
    - dataclasses-json >=0.5.2
    - deprecated >=1.0,<2.0
    - diskcache >=5.2.1
    - docker-py >=5.0.3,<7.0.0
    - docker-image-py >=0.1.10
    - docstring_parser >=0.9.0
    - flyteidl >=1.5.5,<1.6.0
    - fsspec >=2023.3.0
    - gcsfs
    - grpcio >=1.50.0,<2.0
    - grpcio-status >=1.50.0,<2.0
    - importlib-metadata
    - joblib
    - keyring >=18.0.1
    - python-kubernetes >=12.0.1
    - marshmallow-jsonschema >=0.12.0
    - natsort >=7.0.1
    - numpy <1.24.0
    - pandas >=1.0.0,<2.0.0
    - pyarrow >=4.0.0,<11.0.0
    - pyopenssl
    - python-dateutil >=2.1
    - python-json-logger >=2.0.0
    - pytimeparse >=1.1.8,<2.0.0
    - pytz
    - pyyaml
    - requests >=2.18.4,<3.0.0
    - responses >=0.10.7
    - rich
    - rich-click
    - s3fs >0.6.0
    - sortedcontainers >=1.5.9,<3.0.0
    - statsd >=3.0.0,<4.0.0
    - typing_extensions
    - urllib3 >=1.22,<2.0.0
    - wheel >=0.30.0,<1.0.0
    - wrapt >=1.0.0,<2.0.0

test:
  files:
    - example.py
  imports:
    - flytekit
  commands:
    - pip check
    - pyflyte-execute --help
    - pyflyte-fast-execute --help
    - pyflyte-map-execute --help
    - pyflyte --help
    - flyte-cli --help
    - pyflyte run example.py wf --n 500 --mean 42 --sigma 2
  requires:
    - pip

about:
  home: https://github.com/flyteorg/flytekit
  summary: Flyte SDK for Python
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    Flytekit Python is the Python Library for easily authoring, testing, deploying, 
    and interacting with Flyte tasks, workflows, and launch plans.

    - Flyte HomePage: https://flyte.org
    - Flyte Docs: http://docs.flyte.org/

    PyPI: [https://pypi.org/project/flytekit/](https://pypi.org/project/flytekit/)

  doc_url: https://flytecookbook.readthedocs.io/en/latest/
  dev_url: https://github.com/flyteorg/flytekit

extra:
  recipe-maintainers:
    - eapolinario
    - cosmicBboy
    - bmcconeghy
    - asford
    - sugatoray
